title: Hello, world! I'm Zhaochong An
description: > # this means to ignore newlines until "baseurl:"
  I am a senior student major in computer science in Harbin Institute of Technology. Weclome to my homepage!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://1170801121.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Zhaochong An # add your name
author-img: TIM.jpg # add your photo
about-author: I am a senior student major in computer science in Harbin Institute of Technology. Weclome to my homepage! # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: 1170801121 # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: UA-176053492-1 
# Google Analytics
baidu-analysis: 0a3c6d537fbd69ca6ca0cbb578780c85
# Google Analytics
# google_analytics: UA-176053492-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
